parameters:
#    autoplan_site.example.class: Autoplan\SiteBundle\Example

services:
#    autoplan_site.example:
#        class: %autoplan_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
